name: Build and publish site

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5.4.1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: uv sync --frozen --no-install-workspace --python 3.10

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Build site
        run: uv run make build

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: _site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
